name: SceneTools-CI

on:
  push:
    branches: [ "main" ]

jobs:
  trigger-public-repository:
    name: Trigger public repository synchronisation
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ST_SYNC_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
             owner: 'rlty-live',
             repo: 'unity-scene-tools',
             workflow_id: 'sync.yml',
             ref: 'main'
            })
